import { remoteAction, remoteCombineReducers } from "./remote";
import cloneDeep from "lodash/cloneDeep";

// Player {
//   name: "a_name",
//   id: "number"  // 0 - 1 float generated by Math.random()
//   word: "a_word",
//   author: {name: "another_name", id: "number" },
//   hasGuessed: boolean
// };

const lifecycle = (state = { lifecycle: "GET_PLAYERS" }, action) => {
  switch (action.type) {
    case "LIFECYCLE":
      return { lifecycle: action.stage };
    default:
      return state;
  }
};

const players = (state = { players: [] }, action) => {
  switch (action.type) {
    case "ADD_PLAYER": {
      const { name, id } = action;
      return {
        players: [
          ...state.players,
          {
            name,
            id,
            word: "",
            hasGuessed: false,
            author: { name: "", id: "" },
          },
        ],
      };
    }
    case "ASSIGN_AUTHOR": {
      const { targetId, authorName, authorId } = action;
      const players = cloneDeep(state.players);

      const newPlayers = players.map((player) => {
        if (player.id === targetId) {
          player.author = { name: authorName, id: authorId };
        }
        return player;
      });

      return {
        players: newPlayers,
      };
    }
    case "ASSIGN_WORD": {
      const { targetId, word } = action;

      const players = cloneDeep(state.players);
      const newPlayers = players.map((player) => {
        if (player.id === targetId) {
          player.word = word;
        }
        return player;
      });

      return {
        players: newPlayers,
      };
    }
    case "GUESSED_ANSWER": {
      const { targetId } = action;

      const players = cloneDeep(state.players);
      const newPlayers = players.map((player) => {
        if (player.id === targetId) {
          player.hasGuessed = true;
        }
        return player;
      });

      return {
        players: newPlayers,
      };
    }

    default:
      return state;
  }
};

const localId = (state = { localId: null }, action) => {
  switch (action.type) {
    case "LOCAL_ID":
      const { id } = action;
      return { localId: id };
    default:
      return state;
  }
};

const activeTurn = (state = { activeTurn: null }, action) => {
  switch (action.type) {
    case "SET_TURN":
      const { id } = action;
      return { activeTurn: id };
    default:
      return state;
  }
};

export const reducer = remoteCombineReducers(
  { localId },
  { players, lifecycle, activeTurn }
);

// Set player's local ID
export const updateLocalId = (id) => ({
  type: "LOCAL_ID",
  id,
});

// Add a player name to global list of players
export const addPlayer = (name, id) =>
  remoteAction({
    type: "ADD_PLAYER",
    name,
    id,
  });

/**
 * Advance the game's lifecycle
 * @param {*} stage
 * One of "GET_PLAYERS", "WRITE_WORDS", "PLAY", "GAME_OVER"
 */
export const advanceLifecycle = (stage) =>
  remoteAction({
    type: "LIFECYCLE",
    stage,
  });

/**
 * payload = {targetId, author}
 * @param {string} targetId // ID of player being given an author
 * @param {string} authorName // Name of author
 * @param {string} authorId // ID of author
 */
export const assignAuthor = (targetId, authorName, authorId) =>
  remoteAction({
    type: "ASSIGN_AUTHOR",
    targetId,
    authorName,
    authorId,
  });

/**
 * @param {string} targetId // ID of player being given an author
 * @param {string} word // Word to be guessed
 */
export const assignWord = (targetId, word) =>
  remoteAction({
    type: "ASSIGN_WORD",
    targetId,
    word,
  });

export const setTurn = (id) =>
  remoteAction({
    type: "SET_TURN",
    id,
  });

export const guessedAnswer = (targetId) =>
  remoteAction({
    type: "GUESSED_ANSWER",
    targetId,
  });

// Selectors
export const activePlayerSelector = (state) => {
  for (const player of state.players.players) {
    if (player.id === state.activeTurn.activeTurn) {
      return player;
    }
  }
  return null;
};
